const filters = [               
    {id: "Other", label: "Other"},
    {id: "Arts & Collectibles", label: "Arts & Collectibles"},
    {id: "3", label: "Clothing"},
    {id: "Furniture", label: ""},
    {id: "Home - Indoor", label: ""},
    {id: "Toys & Games", label: ""},
    {id: "Sporting Goods & Exercise", label: ""},
    {id: "CDs, DVDs & Blu-ray", label: ""},
    {id: "Home - Outdoor & Garden", label: ""},
    {id: "Books", label: ""},
    {id: "Home Appliances", label: ""},
    {id: "Baby Items", label: ""},
    {id: "Tools", label: ""},
    {id: "Home Renovation Materials", label: ""},
    {id: "Business & Industrial", label: ""},
    {id: "Hobbies & Crafts", label: ""},
    {id: "Electronics", label: ""},
    {id: "Computer Accessories", label: ""},
    {id: "Jewellery & Watches", label: ""},
    {id: "Health & Special Needs", label: ""},
    {id: "Video Games & Consoles", label: ""},
    {id: "Bikes", label: ""},
    {id: "Phones", label: ""},
    {id: "Musical Instruments", label: ""},
    {id: "Audio", label: ""},
    {id: "Computers", label: ""},
    {id: "Cameras & Camcorders", label: ""},
    {id: "TVs & Video", label: ""},
    {id: "Free Stuff", label: ""},
    {id: "Garage Sales", label: ""},
    {id: "Tickets", label: ""},
]

export default filters