export const CREATE_RENTAL_REQUEST = "CREATE_RENTAL_REQUEST";
export const CREATE_RENTAL_SUCCESS = "CREATE_RENTAL_SUCCESS";
export const CREATE_RENTAL_FAIL = "CREATE_RENTAL_FAIL";

export const CONFIRM_RENTAL_REQUEST = "CONFIRM_RENTAL_REQUEST";
export const CONFIRM_RENTAL_SUCCESS = "CONFIRM_RENTAL_SUCCESS";
export const CONFIRM_RENTAL_FAIL = "CONFIRM_RENTAL_FAIL";

export const CREATE_RESCHEDULE_REQUEST = "CREATE_RESCHEDULE_REQUEST";
export const CREATE_RESCHEDULE_SUCCESS = "CREATE_RESCHEDULE_SUCCESS";
export const CREATE_RESCHEDULE_FAIL = "CREATE_RESCHEDULE_FAIL";

export const CONFIRM_RESCHEDULE_REQUEST = "CONFIRM_RESCHEDULE_REQUEST";
export const CONFIRM_RESCHEDULE_SUCCESS = "CONFIRM_RESCHEDULE_SUCCESS";
export const CONFIRM_RESCHEDULE_FAIL = "CONFIRM_RESCHEDULE_FAIL";

export const CANCEL_RENTAL_REQUEST = "CANCEL_RENTAL_REQUEST";
export const CANCEL_RENTAL_SUCCESS = "CANCEL_RENTAL_SUCCESS";
export const CANCEL_RENTAL_FAIL = "CANCEL_RENTAL_FAIL";

export const RENTAL_DETAILS_REQUEST = "RENTAL_DETAILS_REQUEST";
export const RENTAL_DETAILS_SUCCESS = "RENTAL_DETAILS_SUCCESS";
export const RENTAL_DETAILS_FAIL = "RENTAL_DETAILS_FAIL";

export const EXTERNAL_RENTALS_REQUEST = "EXTERNAL_RENTALS_REQUEST";
export const EXTERNAL_RENTALS_SUCCESS = "EXTERNAL_RENTALS_SUCCESS";
export const EXTERNAL_RENTALS_FAIL = "EXTERNAL_RENTALS_FAIL";

export const INTERNAL_RENTALS_REQUEST = "INTERNAL_RENTALS_REQUEST";
export const INTERNAL_RENTALS_SUCCESS = "INTERNAL_RENTALS_SUCCESS";
export const INTERNAL_RENTALS_FAIL = "INTERNAL_RENTALS_FAIL";

export const ALL_RENTALS_REQUEST = "ALL_RENTALS_REQUEST";
export const ALL_RENTALS_SUCCESS = "ALL_RENTALS_SUCCESS";
export const ALL_RENTALS_FAIL = "ALL_RENTALS_FAIL";

export const DELETE_RENTAL_REQUEST = "DELETE_RENTAL_REQUEST";
export const DELETE_RENTAL_SUCCESS = "DELETE_RENTAL_SUCCESS";
export const DELETE_RENTAL_FAIL = "DELETE_RENTAL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";