name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
        - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image from Dockerhub
      run: sudo docker pull shahanb/backend:latest

    - name: Delete old Docker container
      run: sudo docker rm -f backend-container || true

    - name: Run Docker container
      run: sudo docker run -d -p 3001:3001 --name backend-container shahanb/backend
