name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
        - completed

jobs:
  build:
    runs-on: self-hosted

    steps:   
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    
    - name: Pull Docker image from Dockerhub
      run: sudo docker pull shahanb/backend:latest

    - name: Delete old Docker container
      run: sudo docker rm -f backend-container || true

    - name: Run Docker container
      run: sudo docker run -d -p 3001:3001 --name backend-container shahanb/backend
